namePrefix: dev-
nameSuffix: "-001"

resources:
- deployment.yaml
- service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
- source:
    kind: Service
    name: my-nginx
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.command.2
    select:
      group: apps
      kind: Deployment
      name: my-nginx
      version: v1
